---
# tasks file for roles/ubuntu/file
- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Using docker to installweb server
  docker_image:
    name: romeoz/docker-apache-php
    state: present
    source: pull

- name: Using docker to install db server
  docker_image:
    name: mysql/mysql-server:latest
    state: present
    source: pull
